# Generated by Django 5.1.2 on 2024-10-20 16:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
