# Generated by Django 5.1.2 on 2024-10-19 15:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
