# Generated by Django 5.1.2 on 2024-10-20 16:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_standardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
