# Generated by Django 5.1.2 on 2024-10-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wp_connector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wpauthor",
            name="name",
            field=models.CharField(help_text="Display name", max_length=255),
        ),
    ]
