# Generated by Django 5.1.2 on 2024-10-28 14:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_standardpage_excerpt_standardpage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.RichTextBlock", (), {})},
            ),
        ),
    ]
