# Generated by Django 5.1.2 on 2024-10-28 22:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 3),
                    ("blockquote", 6),
                    ("definition_list", 11),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "help_text": "Level of heading",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text to display", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("level", 1), ("text", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Quote to display", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Attribution for quote", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 4), ("attribution", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Term to define", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Definition of term", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("term", 7), ("definition", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("list", 10)]], {}),
                },
            ),
        ),
    ]
