name: Python tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache the virtualenv
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m pip install poetry==1.8.4
          python -m poetry config virtualenvs.in-project true
          python -m poetry install
      - name: Run black
        run: |
          python -m poetry run black --check .
      - name: Run isort
        run: |
          python -m poetry run isort --check .
      - name: Run flake8
        run: |
          python -m poetry run flake8 .
      - name: Run tests
        run: |
          python -m poetry run ./manage.py collectstatic --noinput
          python -m poetry run coverage run manage.py test
          python -m poetry run coverage report
